name: test-ci
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: test Hello
        run: echo Hello