name: test-ci
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.js'
    paths-ignore:
      - 'sub-project/**'
      - '!sub-project/docs/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.js'
    paths-ignore:
      - 'sub-project/**'
      - '!sub-project/docs/**'
jobs:
  skipci:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"
  test:
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - uses: actions/checkout@v3
      - name: test Hello
        run: echo Hello